#!/usr/bin/env bash
# One-shot installer for a fresh Ubuntu 24.04 server (AWS EC2 t4g.small / t3.small or similar).
# Run it from the project folder on the server:   bash deploy/setup-server.sh
# Safe to run again later (e.g. after uploading new code) - it only rebuilds what changed.
set -euo pipefail

APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$APP_DIR"
COMPOSE=(sudo docker compose -f docker-compose.prod.yml --env-file .env)

say() { printf '\n\033[1;32m==> %s\033[0m\n' "$*"; }

# ---------------------------------------------------------------- 1. swap
# 2 GB of RAM is tight while building .NET and Next.js images; 4 GB of swap avoids out-of-memory builds.
if ! sudo swapon --show | grep -q '/swapfile'; then
  say "Adding 4 GB swap"
  sudo fallocate -l 4G /swapfile
  sudo chmod 600 /swapfile
  sudo mkswap /swapfile >/dev/null
  sudo swapon /swapfile
  grep -q '^/swapfile' /etc/fstab || echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab >/dev/null
fi

# ---------------------------------------------------------------- 2. docker
if ! command -v docker >/dev/null || ! sudo docker compose version >/dev/null 2>&1; then
  say "Installing Docker"
  sudo apt-get update -y
  sudo apt-get install -y docker.io docker-compose-v2 docker-buildx
  sudo systemctl enable --now docker
  sudo usermod -aG docker "$USER" || true
fi

# ---------------------------------------------------------------- 3. public address
public_ip() {
  local token
  token=$(curl -s -m 3 -X PUT http://169.254.169.254/latest/api/token \
          -H "X-aws-ec2-metadata-token-ttl-seconds: 60" || true)
  if [[ -n "$token" ]]; then
    curl -s -m 3 -H "X-aws-ec2-metadata-token: $token" http://169.254.169.254/latest/meta-data/public-ipv4 && return
  fi
  curl -s -m 5 https://checkip.amazonaws.com
}
IP="$(public_ip | tr -d '[:space:]')"
[[ "$IP" =~ ^[0-9.]+$ ]] || { echo "Could not detect the public IP"; exit 1; }
SITE="${IP//./-}.sslip.io"

# ---------------------------------------------------------------- 4. .env (secrets are generated once)
if [[ ! -f .env ]]; then
  say "Creating .env with random passwords"
  KAGGLE_USER=""; KAGGLE_KEY_VAL=""
  if [[ -f "$HOME/.kaggle/kaggle.json" ]]; then
    KAGGLE_USER=$(python3 -c 'import json,sys;print(json.load(open(sys.argv[1]))["username"])' "$HOME/.kaggle/kaggle.json")
    KAGGLE_KEY_VAL=$(python3 -c 'import json,sys;print(json.load(open(sys.argv[1]))["key"])' "$HOME/.kaggle/kaggle.json")
  fi
  cat > .env <<EOF
# Generated by deploy/setup-server.sh on $(date -u +%F)
SITE_ADDRESS=$SITE
POSTGRES_USER=aapl
POSTGRES_PASSWORD=$(openssl rand -hex 24)
ADMIN_API_KEY=$(openssl rand -base64 18 | tr -d '/+=' | cut -c1-20)
KAGGLE_USERNAME=$KAGGLE_USER
KAGGLE_KEY=$KAGGLE_KEY_VAL
UPDATE_TIME_UTC=22:30
FORECAST_HORIZON=30
EOF
  chmod 600 .env
else
  CURRENT_SITE=$(grep -E '^SITE_ADDRESS=' .env | cut -d= -f2- || true)
  if [[ -n "$CURRENT_SITE" && "$CURRENT_SITE" == *sslip.io && "$CURRENT_SITE" != "$SITE" ]]; then
    say "Public IP changed - updating SITE_ADDRESS to $SITE"
    sed -i "s/^SITE_ADDRESS=.*/SITE_ADDRESS=$SITE/" .env
  fi
fi

# ---------------------------------------------------------------- 5. build & start
say "Building and starting the stack (first build takes ~10-20 minutes on a small instance)"
"${COMPOSE[@]}" up -d --build --remove-orphans
sudo docker image prune -f >/dev/null || true

SITE_NOW=$(grep -E '^SITE_ADDRESS=' .env | cut -d= -f2-)
ADMIN=$(grep -E '^ADMIN_API_KEY=' .env | cut -d= -f2-)
say "Done"
cat <<EOF

  Website:        https://$SITE_NOW
  Admin password: $ADMIN      (for "จัดการข้อมูล" on the website; also stored in $APP_DIR/.env)

  The first data load + training starts automatically and takes a few minutes.
  Watch it with:  sudo docker compose -f docker-compose.prod.yml logs -f scheduler
  Status:         sudo docker compose -f docker-compose.prod.yml ps

EOF
